export const countryList = [
    {"country": "AF", "countryLabel": "Afghanistan", "currency": "AFN", "symbol": "؋"},
    {"country": "AL", "countryLabel": "Albania", "currency": "ALL", "symbol": "L"},
    {"country": "DZ", "countryLabel": "Algeria", "currency": "DZD", "symbol": "د.ج"},
    {"country": "AR", "countryLabel": "Argentina", "currency": "ARS", "symbol": "$"},
    {"country": "AM", "countryLabel": "Armenia", "currency": "AMD", "symbol": "֏"},
    {"country": "AU", "countryLabel": "Australia", "currency": "AUD", "symbol": "$"},
    {"country": "AT", "countryLabel": "Austria", "currency": "EUR", "symbol": "€"},
    {"country": "AZ", "countryLabel": "Azerbaijan", "currency": "AZN", "symbol": "₼"},
    {"country": "BS", "countryLabel": "Bahamas", "currency": "BSD", "symbol": "$"},
    {"country": "BH", "countryLabel": "Bahrain", "currency": "BHD", "symbol": ".د.ب"},
    {"country": "BD", "countryLabel": "Bangladesh", "currency": "BDT", "symbol": "৳"},
    {"country": "BB", "countryLabel": "Barbados", "currency": "BBD", "symbol": "$"},
    {"country": "BY", "countryLabel": "Belarus", "currency": "BYN", "symbol": "Br"},
    {"country": "BE", "countryLabel": "Belgium", "currency": "EUR", "symbol": "€"},
    {"country": "BZ", "countryLabel": "Belize", "currency": "BZD", "symbol": "$"},
    {"country": "BJ", "countryLabel": "Benin", "currency": "XOF", "symbol": "Fr"},
    {"country": "BT", "countryLabel": "Bhutan", "currency": "BTN", "symbol": "Nu."},
    {"country": "BO", "countryLabel": "Bolivia", "currency": "BOB", "symbol": "Bs."},
    {"country": "BA", "countryLabel": "Bosnia and Herzegovina", "currency": "BAM", "symbol": "KM"},
    {"country": "BW", "countryLabel": "Botswana", "currency": "BWP", "symbol": "P"},
    {"country": "BR", "countryLabel": "Brazil", "currency": "BRL", "symbol": "R$"},
    {"country": "BN", "countryLabel": "Brunei", "currency": "BND", "symbol": "$"},
    {"country": "BG", "countryLabel": "Bulgaria", "currency": "BGN", "symbol": "лв"},
    {"country": "BF", "countryLabel": "Burkina Faso", "currency": "XOF", "symbol": "Fr"},
    {"country": "BI", "countryLabel": "Burundi", "currency": "BIF", "symbol": "Fr"},
    {"country": "CV", "countryLabel": "Cabo Verde", "currency": "CVE", "symbol": "$"},
    {"country": "KH", "countryLabel": "Cambodia", "currency": "KHR", "symbol": "៛"},
    {"country": "CM", "countryLabel": "Cameroon", "currency": "XAF", "symbol": "Fr"},
    {"country": "CA", "countryLabel": "Canada", "currency": "CAD", "symbol": "$"},
    {"country": "CF", "countryLabel": "Central African Republic", "currency": "XAF", "symbol": "Fr"},
    {"country": "TD", "countryLabel": "Chad", "currency": "XAF", "symbol": "Fr"},
    {"country": "CL", "countryLabel": "Chile", "currency": "CLP", "symbol": "$"},
    {"country": "CN", "countryLabel": "China", "currency": "CNY", "symbol": "¥"},
    {"country": "CO", "countryLabel": "Colombia", "currency": "COP", "symbol": "$"},
    {"country": "KM", "countryLabel": "Comoros", "currency": "KMF", "symbol": "Fr"},
    {"country": "CD", "countryLabel": "Democratic Republic of the Congo", "currency": "CDF", "symbol": "Fr"},
    {"country": "CG", "countryLabel": "Republic of the Congo", "currency": "XAF", "symbol": "Fr"},
    {"country": "CR", "countryLabel": "Costa Rica", "currency": "CRC", "symbol": "₡"},
    {"country": "HR", "countryLabel": "Croatia", "currency": "EUR", "symbol": "€"},
    {"country": "CU", "countryLabel": "Cuba", "currency": "CUP", "symbol": "$"},
    {"country": "CY", "countryLabel": "Cyprus", "currency": "EUR", "symbol": "€"},
    {"country": "CZ", "countryLabel": "Czech Republic", "currency": "CZK", "symbol": "Kč"},
    {"country": "DK", "countryLabel": "Denmark", "currency": "DKK", "symbol": "kr"},
    {"country": "DJ", "countryLabel": "Djibouti", "currency": "DJF", "symbol": "Fr"},
    {"country": "DM", "countryLabel": "Dominica", "currency": "XCD", "symbol": "$"},
    {"country": "DO", "countryLabel": "Dominican Republic", "currency": "DOP", "symbol": "$"},
    {"country": "EC", "countryLabel": "Ecuador", "currency": "USD", "symbol": "$"},
    {"country": "EG", "countryLabel": "Egypt", "currency": "EGP", "symbol": "£"},
    {"country": "SV", "countryLabel": "El Salvador", "currency": "USD", "symbol": "$"},
    {"country": "GQ", "countryLabel": "Equatorial Guinea", "currency": "XAF", "symbol": "Fr"},
    {"country": "ER", "countryLabel": "Eritrea", "currency": "ERN", "symbol": "Nfk"},
    {"country": "EE", "countryLabel": "Estonia", "currency": "EUR", "symbol": "€"},
    {"country": "SZ", "countryLabel": "Eswatini", "currency": "SZL", "symbol": "L"},
    {"country": "ET", "countryLabel": "Ethiopia", "currency": "ETB", "symbol": "Br"},
    {"country": "FJ", "countryLabel": "Fiji", "currency": "FJD", "symbol": "$"},
    {"country": "FI", "countryLabel": "Finland", "currency": "EUR", "symbol": "€"},
    {"country": "FR", "countryLabel": "France", "currency": "EUR", "symbol": "€"},
    {"country": "GA", "countryLabel": "Gabon", "currency": "XAF", "symbol": "Fr"},
    {"country": "GM", "countryLabel": "Gambia", "currency": "GMD", "symbol": "D"},
    {"country": "GE", "countryLabel": "Georgia", "currency": "GEL", "symbol": "₾"},
    {"country": "DE", "countryLabel": "Germany", "currency": "EUR", "symbol": "€"},
    {"country": "GH", "countryLabel": "Ghana", "currency": "GHS", "symbol": "₵"},
    {"country": "GR", "countryLabel": "Greece", "currency": "EUR", "symbol": "€"},
    {"country": "GD", "countryLabel": "Grenada", "currency": "XCD", "symbol": "$"},
    {"country": "GT", "countryLabel": "Guatemala", "currency": "GTQ", "symbol": "Q"},
    {"country": "GN", "countryLabel": "Guinea", "currency": "GNF", "symbol": "Fr"},
    {"country": "GW", "countryLabel": "Guinea-Bissau", "currency": "XOF", "symbol": "Fr"},
    {"country": "GY", "countryLabel": "Guyana", "currency": "GYD", "symbol": "$"},
    {"country": "HT", "countryLabel": "Haiti", "currency": "HTG", "symbol": "G"},
    {"country": "HN", "countryLabel": "Honduras", "currency": "HNL", "symbol": "L"},
    {"country": "HU", "countryLabel": "Hungary", "currency": "HUF", "symbol": "Ft"},
    {"country": "IS", "countryLabel": "Iceland", "currency": "ISK", "symbol": "kr"},
    {"country": "IN", "countryLabel": "India", "currency": "INR", "symbol": "₹"},
    {"country": "ID", "countryLabel": "Indonesia", "currency": "IDR", "symbol": "Rp"},
    {"country": "IR", "countryLabel": "Iran", "currency": "IRR", "symbol": "﷼"},
    {"country": "IQ", "countryLabel": "Iraq", "currency": "IQD", "symbol": "ع.د"},
    {"country": "IE", "countryLabel": "Ireland", "currency": "EUR", "symbol": "€"},
    {"country": "IL", "countryLabel": "Israel", "currency": "ILS", "symbol": "₪"},
    {"country": "IT", "countryLabel": "Italy", "currency": "EUR", "symbol": "€"},
    {"country": "JM", "countryLabel": "Jamaica", "currency": "JMD", "symbol": "J$"},
    {"country": "JP", "countryLabel": "Japan", "currency": "JPY", "symbol": "¥"},
    {"country": "JO", "countryLabel": "Jordan", "currency": "JOD", "symbol": "د.ا"},
    {"country": "KZ", "countryLabel": "Kazakhstan", "currency": "KZT", "symbol": "₸"},
    {"country": "KE", "countryLabel": "Kenya", "currency": "KES", "symbol": "Sh"},
    {"country": "KI", "countryLabel": "Kiribati", "currency": "AUD", "symbol": "$"},
    {"country": "KP", "countryLabel": "North Korea", "currency": "KPW", "symbol": "₩"},
    {"country": "KR", "countryLabel": "South Korea", "currency": "KRW", "symbol": "₩"},
    {"country": "KW", "countryLabel": "Kuwait", "currency": "KWD", "symbol": "د.ك"},
    {"country": "KG", "countryLabel": "Kyrgyzstan", "currency": "KGS", "symbol": "с"},
    {"country": "LA", "countryLabel": "Laos", "currency": "LAK", "symbol": "₭"},
    {"country": "LV", "countryLabel": "Latvia", "currency": "EUR", "symbol": "€"},
    {"country": "LB", "countryLabel": "Lebanon", "currency": "LBP", "symbol": "ل.ل"},
    {"country": "LS", "countryLabel": "Lesotho", "currency": "LSL", "symbol": "L"},
    {"country": "LR", "countryLabel": "Liberia", "currency": "LRD", "symbol": "$"},
    {"country": "LY", "countryLabel": "Libya", "currency": "LYD", "symbol": "ل.د"},
    {"country": "LI", "countryLabel": "Liechtenstein", "currency": "CHF", "symbol": "Fr"},
    {"country": "LT", "countryLabel": "Lithuania", "currency": "EUR", "symbol": "€"},
    {"country": "LU", "countryLabel": "Luxembourg", "currency": "EUR", "symbol": "€"},
    {"country": "MG", "countryLabel": "Madagascar", "currency": "MGA", "symbol": "Ar"},
    {"country": "MW", "countryLabel": "Malawi", "currency": "MWK", "symbol": "MK"},
    {"country": "MY", "countryLabel": "Malaysia", "currency": "MYR", "symbol": "RM"},
    {"country": "MV", "countryLabel": "Maldives", "currency": "MVR", "symbol": "ރ."},
    {"country": "ML", "countryLabel": "Mali", "currency": "XOF", "symbol": "Fr"},
    {"country": "MT", "countryLabel": "Malta", "currency": "EUR", "symbol": "€"},
    {"country": "MH", "countryLabel": "Marshall Islands", "currency": "USD", "symbol": "$"},
    {"country": "MR", "countryLabel": "Mauritania", "currency": "MRU", "symbol": "UM"},
    {"country": "MU", "countryLabel": "Mauritius", "currency": "MUR", "symbol": "₨"},
    {"country": "MX", "countryLabel": "Mexico", "currency": "MXN", "symbol": "$"},
    {"country": "FM", "countryLabel": "Micronesia", "currency": "USD", "symbol": "$"},
    {"country": "MD", "countryLabel": "Moldova", "currency": "MDL", "symbol": "L"},
    {"country": "MC", "countryLabel": "Monaco", "currency": "EUR", "symbol": "€"},
    {"country": "MN", "countryLabel": "Mongolia", "currency": "MNT", "symbol": "₮"},
    {"country": "ME", "countryLabel": "Montenegro", "currency": "EUR", "symbol": "€"},
    {"country": "MA", "countryLabel": "Morocco", "currency": "MAD", "symbol": "د.م."},
    {"country": "MZ", "countryLabel": "Mozambique", "currency": "MZN", "symbol": "MT"},
    {"country": "MM", "countryLabel": "Myanmar", "currency": "MMK", "symbol": "Ks"},
    {"country": "NA", "countryLabel": "Namibia", "currency": "NAD", "symbol": "$"},
    {"country": "NR", "countryLabel": "Nauru", "currency": "AUD", "symbol": "$"},
    {"country": "NP", "countryLabel": "Nepal", "currency": "NPR", "symbol": "₨"},
    {"country": "NL", "countryLabel": "Netherlands", "currency": "EUR", "symbol": "€"},
    {"country": "NZ", "countryLabel": "New Zealand", "currency": "NZD", "symbol": "$"},
    {"country": "NI", "countryLabel": "Nicaragua", "currency": "NIO", "symbol": "C$"},
    {"country": "NE", "countryLabel": "Niger", "currency": "XOF", "symbol": "Fr"},
    {"country": "NG", "countryLabel": "Nigeria", "currency": "NGN", "symbol": "₦"},
    {"country": "MK", "countryLabel": "North Macedonia", "currency": "MKD", "symbol": "ден"},
    {"country": "NO", "countryLabel": "Norway", "currency": "NOK", "symbol": "kr"},
    {"country": "OM", "countryLabel": "Oman", "currency": "OMR", "symbol": "ر.ع."},
    {"country": "PK", "countryLabel": "Pakistan", "currency": "PKR", "symbol": "₨"},
    {"country": "PW", "countryLabel": "Palau", "currency": "USD", "symbol": "$"},
    {"country": "PA", "countryLabel": "Panama", "currency": "PAB", "symbol": "B/."},
    {"country": "PG", "countryLabel": "Papua New Guinea", "currency": "PGK", "symbol": "K"},
    {"country": "PY", "countryLabel": "Paraguay", "currency": "PYG", "symbol": "₲"},
    {"country": "PE", "countryLabel": "Peru", "currency": "PEN", "symbol": "S/."},
    {"country": "PH", "countryLabel": "Philippines", "currency": "PHP", "symbol": "₱"},
    {"country": "PL", "countryLabel": "Poland", "currency": "PLN", "symbol": "zł"},
    {"country": "PT", "countryLabel": "Portugal", "currency": "EUR", "symbol": "€"},
    {"country": "QA", "countryLabel": "Qatar", "currency": "QAR", "symbol": "ر.ق"},
    {"country": "RO", "countryLabel": "Romania", "currency": "RON", "symbol": "lei"},
    {"country": "RU", "countryLabel": "Russia", "currency": "RUB", "symbol": "₽"},
    {"country": "RW", "countryLabel": "Rwanda", "currency": "RWF", "symbol": "Fr"},
    {"country": "KN", "countryLabel": "Saint Kitts and Nevis", "currency": "XCD", "symbol": "$"},
    {"country": "LC", "countryLabel": "Saint Lucia", "currency": "XCD", "symbol": "$"},
    {"country": "VC", "countryLabel": "Saint Vincent and the Grenadines", "currency": "XCD", "symbol": "$"},
    {"country": "WS", "countryLabel": "Samoa", "currency": "WST", "symbol": "T"},
    {"country": "SM", "countryLabel": "San Marino", "currency": "EUR", "symbol": "€"},
    {"country": "ST", "countryLabel": "Sao Tome and Principe", "currency": "STN", "symbol": "Db"},
    {"country": "SA", "countryLabel": "Saudi Arabia", "currency": "SAR", "symbol": "ر.س"},
    {"country": "SN", "countryLabel": "Senegal", "currency": "XOF", "symbol": "Fr"},
    {"country": "RS", "countryLabel": "Serbia", "currency": "RSD", "symbol": "дин."},
    {"country": "SC", "countryLabel": "Seychelles", "currency": "SCR", "symbol": "₨"},
    {"country": "SL", "countryLabel": "Sierra Leone", "currency": "SLL", "symbol": "Le"},
    {"country": "SG", "countryLabel": "Singapore", "currency": "SGD", "symbol": "$"},
    {"country": "SK", "countryLabel": "Slovakia", "currency": "EUR", "symbol": "€"},
    {"country": "SI", "countryLabel": "Slovenia", "currency": "EUR", "symbol": "€"},
    {"country": "SB", "countryLabel": "Solomon Islands", "currency": "SBD", "symbol": "$"},
    {"country": "SO", "countryLabel": "Somalia", "currency": "SOS", "symbol": "Sh"},
    {"country": "ZA", "countryLabel": "South Africa", "currency": "ZAR", "symbol": "R"},
    {"country": "SS", "countryLabel": "South Sudan", "currency": "SSP", "symbol": "£"},
    {"country": "ES", "countryLabel": "Spain", "currency": "EUR", "symbol": "€"},
    {"country": "LK", "countryLabel": "Sri Lanka", "currency": "LKR", "symbol": "Rs"},
    {"country": "SD", "countryLabel": "Sudan", "currency": "SDG", "symbol": "ج.س."},
    {"country": "SR", "countryLabel": "Suriname", "currency": "SRD", "symbol": "$"},
    {"country": "SE", "countryLabel": "Sweden", "currency": "SEK", "symbol": "kr"},
    {"country": "CH", "countryLabel": "Switzerland", "currency": "CHF", "symbol": "Fr"},
    {"country": "SY", "countryLabel": "Syria", "currency": "SYP", "symbol": "ل.س"},
    {"country": "TW", "countryLabel": "Taiwan", "currency": "TWD", "symbol": "$"},
    {"country": "TJ", "countryLabel": "Tajikistan", "currency": "TJS", "symbol": "ЅМ"},
    {"country": "TZ", "countryLabel": "Tanzania", "currency": "TZS", "symbol": "Sh"},
    {"country": "TH", "countryLabel": "Thailand", "currency": "THB", "symbol": "฿"},
    {"country": "TL", "countryLabel": "Timor-Leste", "currency": "USD", "symbol": "$"},
    {"country": "TG", "countryLabel": "Togo", "currency": "XOF", "symbol": "Fr"},
    {"country": "TO", "countryLabel": "Tonga", "currency": "TOP", "symbol": "T$"},
    {"country": "TT", "countryLabel": "Trinidad and Tobago", "currency": "TTD", "symbol": "$"},
    {"country": "TN", "countryLabel": "Tunisia", "currency": "TND", "symbol": "د.ت"},
    {"country": "TR", "countryLabel": "Turkey", "currency": "TRY", "symbol": "₺"},
    {"country": "TM", "countryLabel": "Turkmenistan", "currency": "TMT", "symbol": "m"},
    {"country": "TV", "countryLabel": "Tuvalu", "currency": "AUD", "symbol": "$"},
    {"country": "UG", "countryLabel": "Uganda", "currency": "UGX", "symbol": "Sh"},
    {"country": "UA", "countryLabel": "Ukraine", "currency": "UAH", "symbol": "₴"},
    {"country": "AE", "countryLabel": "United Arab Emirates", "currency": "AED", "symbol": "د.إ"},
    {"country": "GB", "countryLabel": "United Kingdom", "currency": "GBP", "symbol": "£"},
    {"country": "US", "countryLabel": "United States", "currency": "USD", "symbol": "$"},
    {"country": "UY", "countryLabel": "Uruguay", "currency": "UYU", "symbol": "$"},
    {"country": "UZ", "countryLabel": "Uzbekistan", "currency": "UZS", "symbol": "с"},
    {"country": "VU", "countryLabel": "Vanuatu", "currency": "VUV", "symbol": "Vt"},
    {"country": "VE", "countryLabel": "Venezuela", "currency": "VES", "symbol": "Bs.S."},
    {"country": "VN", "countryLabel": "Vietnam", "currency": "VND", "symbol": "₫"},
    {"country": "YE", "countryLabel": "Yemen", "currency": "YER", "symbol": "﷼"},
    {"country": "ZM", "countryLabel": "Zambia", "currency": "ZMW", "symbol": "ZK"},
    {"country": "ZW", "countryLabel": "Zimbabwe", "currency": "ZWL", "symbol": "$"}
  ]
  